language: python

sudo: false

python:
 - '2.7'
 - '3.5'
 - '3.6'

install:
 - pip install -r requirements.txt

script:
 - flake8 documentcloud
 - coverage run setup.py test

after_success:
  - coveralls

env:
  global:
    # Encrypted DOCUMENTCLOUD_TEST_USERNAME
    - secure: "mt7PbdPrHREewNkZE+hV/HILK+67IYVl2F/SZi57VZYx7zBX2+jwZbAAbiWwGrOG9zqgqGiovH+Bx1NAPDm6V0vdlEaXzxhqpKxd4KKWCocL5tZP+6mXbN36Cifm04TIvFUBG0auCR2OMoewxgaY0a/vr6+KYYj37uAlUPhfBcA="
    # Encrypted DOCUMENTCLOUD_TEST_PASSWORD
    - secure: "ZoGrJ9lPyDPDRwMcL5Wx+t+BNPnwpuRy2d4c6z/lTYhdyGwHycoQJCMcvgMkKm/VQP76iLR2efuwV4GUGPRD4YkIBqEgYrLtEvxHUAoLQoo3+uylPrmfZDQtLTmXN5ZKR+dSGFLs9mMQhU0zARpdgSIMFlz2xgFKMpjvzN3lHmc="
