name: Run Pre-recorded Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -e ".[test]"
      - name: Run pre-recorded tests
        run: make test
  pylint-and-black:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -e ".[dev,test]"
      - name: Run pylint and black on ./documentcloud and ./tests
        run: |
          pylint ./documentcloud ./tests
          black --check ./documentcloud ./tests